//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiGame.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        internal static string ad {
            get {
                return ResourceManager.GetString("ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ay.
        /// </summary>
        internal static string ay {
            get {
                return ResourceManager.GetString("ay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocak.
        /// </summary>
        internal static string ay1 {
            get {
                return ResourceManager.GetString("ay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekim.
        /// </summary>
        internal static string ay10 {
            get {
                return ResourceManager.GetString("ay10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasım.
        /// </summary>
        internal static string ay11 {
            get {
                return ResourceManager.GetString("ay11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aralık.
        /// </summary>
        internal static string ay12 {
            get {
                return ResourceManager.GetString("ay12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubat.
        /// </summary>
        internal static string ay2 {
            get {
                return ResourceManager.GetString("ay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mart.
        /// </summary>
        internal static string ay3 {
            get {
                return ResourceManager.GetString("ay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nisan.
        /// </summary>
        internal static string ay4 {
            get {
                return ResourceManager.GetString("ay4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayıs.
        /// </summary>
        internal static string ay5 {
            get {
                return ResourceManager.GetString("ay5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haziran.
        /// </summary>
        internal static string ay6 {
            get {
                return ResourceManager.GetString("ay6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temmuz.
        /// </summary>
        internal static string ay7 {
            get {
                return ResourceManager.GetString("ay7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağustos.
        /// </summary>
        internal static string ay8 {
            get {
                return ResourceManager.GetString("ay8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eylül.
        /// </summary>
        internal static string ay9 {
            get {
                return ResourceManager.GetString("ay9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş Bırakılamaz !.
        /// </summary>
        internal static string bos {
            get {
                return ResourceManager.GetString("bos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceo.
        /// </summary>
        internal static string ceo {
            get {
                return ResourceManager.GetString("ceo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet Seçiniz.....
        /// </summary>
        internal static string cinsiyet {
            get {
                return ResourceManager.GetString("cinsiyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet Seçiniz.
        /// </summary>
        internal static string cinsiyet2 {
            get {
                return ResourceManager.GetString("cinsiyet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi :.
        /// </summary>
        internal static string d1 {
            get {
                return ResourceManager.GetString("d1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string d2 {
            get {
                return ResourceManager.GetString("d2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksik Karakter!.
        /// </summary>
        internal static string eksik1 {
            get {
                return ResourceManager.GetString("eksik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkek.
        /// </summary>
        internal static string erkek {
            get {
                return ResourceManager.GetString("erkek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Ad.
        /// </summary>
        internal static string fad {
            get {
                return ResourceManager.GetString("fad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string g1 {
            get {
                return ResourceManager.GetString("g1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta :.
        /// </summary>
        internal static string g2 {
            get {
                return ResourceManager.GetString("g2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre :.
        /// </summary>
        internal static string g3 {
            get {
                return ResourceManager.GetString("g3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string g4 {
            get {
                return ResourceManager.GetString("g4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün.
        /// </summary>
        internal static string gun {
            get {
                return ResourceManager.GetString("gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Onayı.
        /// </summary>
        internal static string guvenonay {
            get {
                return ResourceManager.GetString("guvenonay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harf Giriniz.
        /// </summary>
        internal static string hgir {
            get {
                return ResourceManager.GetString("hgir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadın.
        /// </summary>
        internal static string kadin {
            get {
                return ResourceManager.GetString("kadin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string kayit {
            get {
                return ResourceManager.GetString("kayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodu.
        /// </summary>
        internal static string kod {
            get {
                return ResourceManager.GetString("kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        internal static string kod2 {
            get {
                return ResourceManager.GetString("kod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Gönderildi.
        /// </summary>
        internal static string kod3 {
            get {
                return ResourceManager.GetString("kod3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Hatalı.
        /// </summary>
        internal static string kodhata {
            get {
                return ResourceManager.GetString("kodhata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string kullanici {
            get {
                return ResourceManager.GetString("kullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre (En az 8 Haneli).
        /// </summary>
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar.
        /// </summary>
        internal static string passagain {
            get {
                return ResourceManager.GetString("passagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler Eşleşmiyor.
        /// </summary>
        internal static string passes {
            get {
                return ResourceManager.GetString("passes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        internal static string posta {
            get {
                return ResourceManager.GetString("posta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seçiniz.
        /// </summary>
        internal static string sec {
            get {
                return ResourceManager.GetString("sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevgili.
        /// </summary>
        internal static string sev {
            get {
                return ResourceManager.GetString("sev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        internal static string soyad {
            get {
                return ResourceManager.GetString("soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıl.
        /// </summary>
        internal static string yil {
            get {
                return ResourceManager.GetString("yil", resourceCulture);
            }
        }
    }
}
